import type { Metadata } from "next";
import { GeistSans, GeistMono } from "geist/font";
import "./globals.css";
import { FpjsProvider } from '@fingerprintjs/fingerprintjs-pro-react';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GeistSans.className} antialiased`}>
        <FpjsProvider
          loadOptions={{
            apiKey: "NuaxGMdDvGzhOByJFPn8",
            region: "ap",
          }}
        >
          {children}
        </FpjsProvider>
      </body>
    </html>
  );
}